"""add bug_analyses table

Revision ID: 0ccd3713f19e
Revises: e3ee99c0ab66
Create Date: 2026-04-27 12:27:16.295503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ccd3713f19e'
down_revision: Union[str, Sequence[str], None] = 'e3ee99c0ab66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('bug_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fix_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('fix_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fix_complexity', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('fix_effort_estimate', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('fix_complexity_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_tests_miss', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_regression', sa.Boolean(), nullable=True),
    sa.Column('regression_introduced_by', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('regression_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similar_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_of_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suspect_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_analyses_run', 'bug_analyses', ['run_id'], unique=False)
    op.create_index(op.f('ix_bug_analyses_run_id'), 'bug_analyses', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_analyses_run_id'), table_name='bug_analyses')
    op.drop_index('ix_bug_analyses_run', table_name='bug_analyses')
    op.drop_table('bug_analyses')
    # ### end Alembic commands ###
