"""initial schema

Revision ID: e3ee99c0ab66
Revises: 
Create Date: 2026-04-24 10:36:05.856007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3ee99c0ab66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ticket_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('project_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('issue_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('parent_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_key', name='uq_jira_tickets_key')
    )
    op.create_index(op.f('ix_jira_tickets_parent_key'), 'jira_tickets', ['parent_key'], unique=False)
    op.create_index(op.f('ix_jira_tickets_project_key'), 'jira_tickets', ['project_key'], unique=False)
    op.create_index(op.f('ix_jira_tickets_ticket_key'), 'jira_tickets', ['ticket_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('jira_account_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_jira_account_id'), 'users', ['jira_account_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', postgresql.ENUM('plan', 'case', name='feedback_target'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('signal', postgresql.ENUM('up', 'down', name='feedback_signal'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_events_created_at', 'feedback_events', ['created_at'], unique=False)
    op.create_index('ix_feedback_events_target', 'feedback_events', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_feedback_events_user_id'), 'feedback_events', ['user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_type', postgresql.ENUM('test_plan', 'test_plan_multi', 'bug_lens', 'bug_lens_multi', 'summarize', name='run_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('ok', 'error', name='run_status'), nullable=False),
    sa.Column('ticket_keys', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('had_pr_diff', sa.Boolean(), nullable=False),
    sa.Column('had_figma', sa.Boolean(), nullable=False),
    sa.Column('had_parent', sa.Boolean(), nullable=False),
    sa.Column('linked_ticket_count', sa.Integer(), nullable=False),
    sa.Column('pr_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('cost_usd >= 0', name='ck_runs_cost_nonneg'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_runs_latency_nonneg'),
    sa.CheckConstraint('output_tokens >= 0', name='ck_runs_output_tokens_nonneg'),
    sa.CheckConstraint('prompt_tokens >= 0', name='ck_runs_prompt_tokens_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_created_at_desc', 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_run_type'), 'runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index('ix_runs_user_created_at', 'runs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('generated_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('format', postgresql.ENUM('markdown', 'jira', 'json', name='plan_format'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_plan_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('case_count >= 0', name='ck_generated_plans_case_count_nonneg'),
    sa.CheckConstraint('version >= 1', name='ck_generated_plans_version_positive'),
    sa.ForeignKeyConstraint(['previous_plan_id'], ['generated_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_plans_previous_plan_id'), 'generated_plans', ['previous_plan_id'], unique=False)
    op.create_index('ix_generated_plans_run', 'generated_plans', ['run_id'], unique=False)
    op.create_index(op.f('ix_generated_plans_run_id'), 'generated_plans', ['run_id'], unique=False)
    op.create_table('plan_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.CheckConstraint('position >= 0', name='ck_plan_test_cases_position_nonneg'),
    sa.ForeignKeyConstraint(['plan_id'], ['generated_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_test_cases_category'), 'plan_test_cases', ['category'], unique=False)
    op.create_index(op.f('ix_plan_test_cases_plan_id'), 'plan_test_cases', ['plan_id'], unique=False)
    op.create_index('ix_plan_test_cases_plan_position', 'plan_test_cases', ['plan_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_test_cases_plan_position', table_name='plan_test_cases')
    op.drop_index(op.f('ix_plan_test_cases_plan_id'), table_name='plan_test_cases')
    op.drop_index(op.f('ix_plan_test_cases_category'), table_name='plan_test_cases')
    op.drop_table('plan_test_cases')
    op.drop_index(op.f('ix_generated_plans_run_id'), table_name='generated_plans')
    op.drop_index('ix_generated_plans_run', table_name='generated_plans')
    op.drop_index(op.f('ix_generated_plans_previous_plan_id'), table_name='generated_plans')
    op.drop_table('generated_plans')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index('ix_runs_user_created_at', table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_run_type'), table_name='runs')
    op.drop_index('ix_runs_created_at_desc', table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_feedback_events_user_id'), table_name='feedback_events')
    op.drop_index('ix_feedback_events_target', table_name='feedback_events')
    op.drop_index('ix_feedback_events_created_at', table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index(op.f('ix_users_jira_account_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jira_tickets_ticket_key'), table_name='jira_tickets')
    op.drop_index(op.f('ix_jira_tickets_project_key'), table_name='jira_tickets')
    op.drop_index(op.f('ix_jira_tickets_parent_key'), table_name='jira_tickets')
    op.drop_table('jira_tickets')
    # ### end Alembic commands ###
