"""Is there a newer Claude model than the one this bot is pinned to?

Run by the weekly model-bump workflow. Queries the Models API, compares what
Anthropic serves against DEFAULT_CLAUDE_MODEL, and reports the newest model in
the same family.

Deliberately does not edit anything. It reports; the workflow opens a PR; a
person merges it. A model bump changes what every plan is generated by, and
the per-model request quirks in model_capabilities.py have to be checked by
hand each time — the last bump found `temperature` removed, thinking on by
default, and the response shape changed with it.

    python scripts/check_for_newer_model.py          # human-readable
    python scripts/check_for_newer_model.py --github # writes GITHUB_OUTPUT
"""

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import httpx

from src.app.model_capabilities import DEFAULT_CLAUDE_MODEL, parse_model


def newer_model(current: str, available: list[dict]) -> dict | None:
    """The newest model in `current`'s family, or None if we are already on it.

    Compares parsed (major, minor) rather than release date: version ordering
    is what the capability table in model_capabilities.py is keyed on, and a
    dated snapshot of an older model can be published after a newer model
    ships.
    """
    parsed_current = parse_model(current)
    if parsed_current is None:
        return None
    family, version = parsed_current

    best = None
    for model in available:
        p = parse_model(model.get("id", ""))
        if p is None or p[0] != family:
            continue
        if p[1] <= version:
            continue
        if best is None or p[1] > parse_model(best["id"])[1]:
            best = model
    return best


def fetch_models(api_key: str) -> list[dict]:
    out, params = [], {"limit": 100}
    with httpx.Client(timeout=60) as client:
        while True:
            r = client.get(
                "https://api.anthropic.com/v1/models",
                headers={"x-api-key": api_key, "anthropic-version": "2023-06-01"},
                params=params,
            )
            r.raise_for_status()
            body = r.json()
            out.extend(body.get("data") or [])
            if not body.get("has_more"):
                return out
            params = {"limit": 100, "after_id": body["last_id"]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--github", action="store_true",
                    help="write found/model/name to GITHUB_OUTPUT")
    args = ap.parse_args()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("ANTHROPIC_API_KEY is not set — cannot ask which models exist. "
                 "This is a missing credential, not an answer of 'no newer model'.")

    models = fetch_models(api_key)
    found = newer_model(DEFAULT_CLAUDE_MODEL, models)

    print(f"pinned:    {DEFAULT_CLAUDE_MODEL}")
    print(f"available: {len(models)} models")
    if found:
        print(f"NEWER:     {found['id']}  ({found.get('display_name', '')})")
    else:
        print("NEWER:     none — already on the newest in its family")

    if args.github and (path := os.environ.get("GITHUB_OUTPUT")):
        with open(path, "a") as f:
            f.write(f"found={'true' if found else 'false'}\n")
            if found:
                f.write(f"model={found['id']}\n")
                f.write(f"name={found.get('display_name', found['id'])}\n")
                f.write(f"current={DEFAULT_CLAUDE_MODEL}\n")


if __name__ == "__main__":
    main()
